config/routes.rb
Rails.application.routes.draw do


  resources :charges
  root 'static#home' 
  get '/cursus', 		to: 'static#cursus'
  get '/faq', 			to: 'static#faq'
  get '/philosophie', 	to: 'static#philosophie'
  get '/inscription',	to: 'static#inscription'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/contact', to: 'messages#new'
  post '/contact', to: 'messages#create'

  
  get '/survey', to: 'surveys#new'
  post '/survey', to: 'surveys#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message 
	include ActiveModel::Model
	attr_accessor :first_name, :last_name, :email, :body
	validates :first_name, :last_name, :email, :body, presence: true
end

app/models/survey.rb
class Survey
	include ActiveModel::Model
	attr_accessor :first_name, :last_name, :age, :email, :body
	validates :first_name, :last_name, :age, :email, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 100

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'paiment enregistrement',
      :currency    => 'eur'
    )


  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
  	@message = Message.new
  end


  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact_me(@message).deliver_now
      redirect_to contact_path, notice: "Merci pour ton message, Il a bien été envoyé on te répondra très vite."
    else
      render :new
    end
  end

  private

  def message_params
    params.require(:message).permit(:first_name, :last_name, :email, :body)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def cursus
  end

  def philosophie
  end

  def faq
  end

  def contact
  end

  
  def inscription
  end

  
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def new
  	@surveys = Survey.new
  end

  def create
  	survey_params = params.require(:survey).permit(:first_name, :last_name, :age, :email, :body)
  	@survey = Survey.new survey_params
  	p survey_params
  	session = GoogleDrive::Session.from_config("./config/client_details.json")
  	ws = session.spreadsheet_by_key("1jQzb6wLJ09Ve5hzmDwe1u7OClHM4DFBjlwpFbQ9GSUU").worksheets[0]

  	ws.insert_rows(ws.num_rows + 1, [[survey_params[:first_name], survey_params[:last_name], survey_params[:age], survey_params[:email], survey_params[:body]]])
  	ws.save
  	redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/charges/create.html.erb
<div style="margin-top: 20em; margin-left: 25em; white-space: normal;">
<%= button_to("Finir mon inscription en remplissant le formulaire complet d'inscription, il doit être rempli dès maintenant",  survey_path, :class => "btn btn-success") %>
</div>

app/views/layouts/_header.html.erb
 <!--
        ==================================================
        Header Section Start
        ================================================== -->
        <header id="top-bar" class="navbar-fixed-top animated-header">
            <div class="container">
                <div class="navbar-header">
                    <!-- responsive nav button -->
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </button>
                    <!-- /responsive nav button -->
                    
                    <!-- logo -->
                    <div class="navbar-brand">
                        <a >
                           <%=link_to  image_tag('logo.png', :id => 'logo'), root_path%>
                        </a>
                    </div>
                    <!-- /logo -->
                </div>
                <!-- main menu -->
                <nav class="collapse navbar-collapse navbar-right" role="navigation">
                    <div class="main-menu">
                        <ul class="nav navbar-nav navbar-right">
                            <li><%=link_to 'Home', root_path%></li>
                            <li><%=link_to 'Cursus', cursus_path%></li>
                            <li><%=link_to 'Philosophie', philosophie_path%></li>
                            <li><%=link_to 'F.A.Q.', faq_path%></li>
                            <li><%=link_to 'Contact', contact_path%></li>
                            <li><%=link_to "S'inscrire", inscription_path%></li>
                        </ul>
                    </div>
                </nav>
                <!-- /main nav -->
            </div>
        </header>
        

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The hacking project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
   <!-- Template CSS Files
        ================================================== -->
        <!-- Twitter Bootstrs CSS -->
        <link rel="stylesheet" href="timer/css/bootstrap.min.css">
        <!-- Ionicons Fonts Css -->
        <link rel="stylesheet" href="timer/css/ionicons.min.css">
        <!-- animate css -->
        <link rel="stylesheet" href="timer/css/animate.css">
        <!-- Hero area slider css-->
        <link rel="stylesheet" href="timer/css/slider.css">
        <!-- owl craousel css -->
        <link rel="stylesheet" href="timer/css/owl.carousel.css">
        <link rel="stylesheet" href="timer/css/owl.theme.css">
        <link rel="stylesheet" href="timer/css/jquery.fancybox.css">
        <!-- template main css file -->
        <link rel="stylesheet" href="timer/css/main.css">
        <link rel="stylesheet" href="timer/css/lasthope.css">
        <!-- responsive css -->
        <link rel="stylesheet" href="timer/css/responsive.css">
        
  </head>

  <body>
  <%= render 'layouts/header'%>
    <%= yield %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
        <!-- modernizr js -->
        <script src="timer/js/vendor/modernizr-2.6.2.min.js"></script>
        <!-- jquery -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <!-- owl carouserl js -->
        <script src="timer/js/owl.carousel.min.js"></script>
        <!-- bootstrap js -->
        <script src="timer/js/bootstrap.min.js"></script>
        <!-- wow js -->
        <script src="timer/js/wow.min.js"></script>
        <!-- slider js -->
        <script src="timer/js/slider.js"></script>
        <script src="timer/js/jquery.fancybox.js"></script>
        <!-- template main js -->
        <script src="timer/js/main.js"></script>
        <script src="timer/js/map.js"></script>
        <script src="timer/js/process_stripe.js"></script>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
  		<meta charset="utf-8">
   		<meta name="viewport" content="width=device-width, initial-scale=1.0">
   		<title>The Hacking Project</title>
  		<link rel="stylesheet" href="timer/css/bootstrap.min.css">
        <!-- Ionicons Fonts Css -->
        <link rel="stylesheet" href="timer/css/ionicons.min.css">
        <!-- animate css -->
        <link rel="stylesheet" href="timer/css/animate.css">
        <!-- Hero area slider css-->
        <link rel="stylesheet" href="timer/css/slider.css">
        <!-- owl craousel css -->
        <link rel="stylesheet" href="timer/css/owl.carousel.css">
        <link rel="stylesheet" href="timer/css/owl.theme.css">
        <link rel="stylesheet" href="timer/css/jquery.fancybox.css">
        <!-- template main css file -->
        <link rel="stylesheet" href="timer/css/main.css">
        <link rel="stylesheet" href="timer/css/lasthope.css">
        <!-- responsive css -->
        <link rel="stylesheet" href="timer/css/responsive.css">
        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
  </head>
  <body>
  <%= render 'layouts/header'%>
    <%= yield %>
    	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- modernizr js -->
        <script src="timer/js/vendor/modernizr-2.6.2.min.js"></script>
        <!-- jquery -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <!-- owl carouserl js -->
        <script src="timer/js/owl.carousel.min.js"></script>
        <!-- bootstrap js -->
        <script src="timer/js/bootstrap.min.js"></script>
        <!-- wow js -->
        <script src="timer/js/wow.min.js"></script>
        <!-- slider js -->
        <script src="timer/js/slider.js"></script>
        <script src="timer/js/jquery.fancybox.js"></script>
        <!-- template main js -->
        <script src="timer/js/main.js"></script>
        <script src="timer/js/map.js"></script>
        <script src="timer/js/process_stripe.js"></script>
  </body>
</html>

app/views/messages/new.html.erb
        <!-- 
        ================================================== 
            Contact Section Start
        ================================================== -->
        <section id="contact-section">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="block">
                            <h2 class="subtitle wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".3s">Contactez-nous</h2>
                            <p class="subtitle-des wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".5s">
                                Une quesrtion? Un point à éclaircir? Nous serons heureux de te répondre
                            </p>
                            <div class="contact-form">
                                
                        		<p style="color: green; font-size: 18px; font-weight: 900;"><%= notice %></p>
                        		
                        		<br>
                        		<br>

								
								<%= form_for @message, url: contact_path do |f| %>
								  
								  <%= @message.errors.full_messages.join(', ') %>
								  <div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".6s">
								  <%= f.text_field :first_name, placeholder: 'Prenom',class: "form-control" %>
								  </div>
								  <div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".6s">
								  <%= f.text_field :last_name, placeholder: 'Nom',class: "form-control" %>
								  </div>
								  <div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".6s">
								  <%= f.email_field :email, placeholder: 'email',class: "form-control" %>
								  </div>
								  <div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".6s">
								  <%= f.text_area :body, placeholder: 'Message',class: "form-control", id: "message" %>
								  </div>
								  
								  <%= f.submit 'Envoyer mon message <3'%>
								  
								  <% end %>
                                
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                         <div class="map-area">
                            <h2 class="subtitle  wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".3s">Nous trouver?</h2>
                            <p class="subtitle-des wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".5s">
                                Nous sommes partout à la fois. Paris, Marseille, Lyon, Lille, Bordeaux sont des villes où nous sommes comme chez nous. Nous sommes nomades.
                                
                            </p>
                          	<div id="map" style=" height: 400px; width: 555px;">
								<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDyr4bpHn6kpIZnx10ruKC1QPx7ZvnoXx8&callback=initMap"></script>   
							</div>
                        </div>
                    </div>
                </div>
                <div class="row address-details">
                    <div class="col-md-4">
                        <div class="address wow fadeInLeft" data-wow-duration="500ms" data-wow-delay=".3s">
                            <i class="ion-ios-location-outline"></i>
                            <p>47 rue du caire <br>75002 Paris</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="email wow fadeInLeft" data-wow-duration="500ms" data-wow-delay=".7s">
                            <i class="ion-ios-email-outline"></i>
                            <p>Un seul email pour nous joindre:<br>bonjour@thehackingproject.org</p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="phone wow fadeInLeft" data-wow-duration="500ms" data-wow-delay=".9s">
                            <i class="ion-ios-telephone-outline"></i>
                            <p>Téléphone<br>06 95 46 60 80</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>






        <!-- 
        ================================================== 
            Call To Action Section Start
        ================================================== -->
        <section id="call-to-action">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="block">
                            <h2 class="title wow fadeInDown" data-wow-delay=".3s" data-wow-duration="500ms">Vous n'en pouvez plus de lire notre site? Envie de sauter le pas? </h1>
                            
                            <%= link_to ("Je veux m'inscrire"), inscription_path, class:"btn btn-default btn-contact wow fadeInDown"%>
                        </div>
                    </div>
                    
                </div>
            </div>
        </section>


                           

app/views/surveys/new.html.erb
<br>
<br>
<br>
<br>
<br>



<div>

<%= form_for @surveys, url: survey_path do |f| %>
								  
<%= @surveys.errors.full_messages.join(', ') %>
<div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".6s">
<%= f.text_field :first_name, placeholder: 'Prenom',class: "form-control" %>
</div>
<div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".6s">
<%= f.text_field :last_name, placeholder: 'Nom',class: "form-control" %>
</div>
<div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".6s">
<%= f.number_field :age, placeholder: 'age',class: "form-control" %>
</div>
<div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".6s">
<%= f.email_field :email, placeholder: 'email',class: "form-control" %>
</div>
<div class="form-group wow fadeInDown" data-wow-duration="500ms" data-wow-delay=".6s">
<%= f.text_area :body, placeholder: 'Message',class: "form-control", id: "message" %>
</div>
								  
<%= f.submit 'Envoyer mon formulaire <3'%>
								  
<% end %>

</div>